services:
  app:
    image: al-ai-assistant:v1.3.2
    container_name: al-ai-assistant
    
    env_file:
      - .env
    
    environment:
      DATABASE: /app/data/ai_chat.db
    
    ports:
      - "9999:8000"
    
    depends_on:
      mysql:
        condition: service_healthy

      redis:
        condition: service_healthy
    
    volumes:
      - al-ai-data:/app/data
  
  mysql:
    image: mysql:8.4
    container_name: al-ai-mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: al_ai
      MYSQL_USER: ai_user
      MYSQL_PASSWORD: ai_password
    
    
    volumes:
      - al-ai-mysql-data:/var/lib/mysql

    healthcheck:
      test: [
        "CMD", 
        "mysqladmin",
        "ping",
        "-h",
        "localhost",
        "-uai_user",
        "-pai_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: al-ai-redis

    command: redis-server --appendonly yes

    volumes:
      - al-ai-redis-data:/data

    healthcheck:
      test: [
        "CMD",
         "redis-cli",
         "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  
  al-ai-data:
    external: true
  
  al-ai-mysql-data:
    driver: local

  al-ai-redis-data: